name: Build and Publish Wordpress containers

on:
  push:
    branches: 
      - 'release/**'
      - 'feature/**'
      - develop
    tags:
      - '*'
  pull_request:
    branches: 
      - main
      - 'release/**'
      - develop

env:
  NEXUS_DOCKER_USER: ${{ secrets.HOME_NEXUS_DOCKER_USER }}

jobs:
  build-and-publish:
    runs-on: [ self-hosted, medium, build ]
    container:
      image: nexus.jamesjonesconsulting.com:5443/jamesjonesconsulting/podman-dind-like:latest
      options: --userns=keep-id --group-add keep-groups --privileged --user root --security-opt seccomp=unconfined
      credentials:
        username: ${{ secrets.HOME_NEXUS_DOCKER_USER }}
        password: ${{ secrets.HOME_NEXUS_DOCKER_PASSWORD }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - id: set-matrix
        run: |
          WP_VERSIONS=( $(curl --silent "https://api.github.com/repos/Wordpress/Wordpress/tags" | jq '.[] | .name' | head -n 10) )
          matrix=$(jq -R -s '{versions: .}' <<< "${WP_VERSIONS[@]}")
          echo $matrix
          echo $matrix | jq .
          # echo "::set-output name=matrix::$matrix"
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

