name: Build and Publish Wordpress containers

on:
  push:
    branches: 
      - 'release/**'
      - 'feature/**'
      - develop
    tags:
      - '*'
  pull_request:
    branches: 
      - main
      - 'release/**'
      - develop

env:
  NEXUS_DOCKER_USER: ${{ secrets.HOME_NEXUS_DOCKER_USER }}
  NEXUS_PROXY_REGISTRY: nexus.jamesjonesconsulting.com:5444
  NEXUS_REGISTRY: nexus.jamesjonesconsulting.com:5443
  version_filter: 6
  version_count: 10
  matrix_options: |
    types:
      - apache
      - fpm
      - fpm-alpine
jobs:
  matrix:
    runs-on: [ self-hosted, medium, build ]
    container:
      image: nexus.jamesjonesconsulting.com:5443/jamesjonesconsulting/podman-dind-like:latest
      options: --userns=keep-id --group-add keep-groups --privileged --user root --security-opt seccomp=unconfined
      credentials:
        username: ${{ secrets.HOME_NEXUS_DOCKER_USER }}
        password: ${{ secrets.HOME_NEXUS_DOCKER_PASSWORD }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - id: set-matrix
        run: |
          matrix_options=$(echo -n "${{ env.matrix_options}}" | yq r -j -)
          WP_VERSIONS=( $(curl --silent "https://api.github.com/repos/Wordpress/Wordpress/tags" | jq '.[] | .name' | awk '/^"${{ env.version_filter }}/' | head -n ${{ env.version_count }}) )
          matrix=$(jq -s '{version: ., type: ["apache","fpm","fpm-alpine"]}' <<< "${WP_VERSIONS[@]}" | jq -c .)
          jq --slurp 'add' <(echo "$matrix") <(echo "$matrix_options")
          echo $matrix
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
  check-matrix:
    runs-on: [ self-hosted, medium, build ]
    needs: matrix
    steps:
      - name: Check matrix definition
        run: |
          matrix='${{ needs.matrix.outputs.matrix }}'
          echo $matrix
  build-and-publish:
    needs: check-matrix
    timeout-minutes: 720
    runs-on: [ self-hosted, medium, build ]
    container:
      image: nexus.jamesjonesconsulting.com:5443/jamesjonesconsulting/podman-dind-like:latest
      options: --userns=keep-id --group-add keep-groups --privileged --user root --security-opt seccomp=unconfined
      credentials:
        username: ${{ secrets.HOME_NEXUS_DOCKER_USER }}
        password: ${{ secrets.HOME_NEXUS_DOCKER_PASSWORD }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.NEXUS_REGISTRY }}
          username: ${{ secrets.HOME_NEXUS_DOCKER_USER }}
          password: ${{ secrets.HOME_NEXUS_DOCKER_PASSWORD }}
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.NEXUS_PROXY_REGISTRY }}
          username: ${{ secrets.HOME_NEXUS_DOCKER_USER }}
          password: ${{ secrets.HOME_NEXUS_DOCKER_PASSWORD }}
      # This requires docker buildx which podman doesn't support
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: ${{ matrix.registry }}/${{ env.IMAGE_NAME }}      
      # - name: Build and push Docker images
      #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}          
      - name: Build the Docker image
        run: |
          IMAGE_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]') 
          if [[ "$GITHUB_REF" =~ ^refs/tags.* ]]; then
            VERSION=$GITHUB_REF_NAME
          else
            VERSION=$(echo "${GITHUB_REF_NAME}" | sed 's|/|-|g')
          fi
          podman build --file Dockerfile.${{ matrix.type }} --tag "${{ env.NEXUS_REGISTRY }}/$IMAGE_NAME/${{ matrix.type }}/${{ matrix.version }}:$VERSION" --build-arg ARTIFACTORY=${{ env.NEXUS_PROXY_REGISTRY }} --build-arg TAG_VERSION=${{ matrix.version }} --build-arg TAG_TYPE=${{ matrix.type }}
          podman push "${{ env.NEXUS_REGISTRY }}/$IMAGE_NAME/${{ matrix.type }}/${{ matrix.version }}:$VERSION"
          if [[ "$GITHUB_REF" =~ ^refs/tags.* ]]; then
            podman tag "${{ env.NEXUS_REGISTRY }}/$IMAGE_NAME/${{ matrix.type }}/${{ matrix.version }}:$VERSION" "${{ env.NEXUS_REGISTRY }}/$IMAGE_NAME/${{ matrix.type }}/${{ matrix.version }}:latest"
            podman push "${{ env.NEXUS_REGISTRY }}/$IMAGE_NAME/${{ matrix.type }}/${{ matrix.version }}:latest"
          fi
