name: Deploy Wordpress container

on:
  push:
    branches: 
      - 'release/**'
      - 'feature/**'
      - develop
    tags:
      - '*'
  pull_request:
    branches: 
      - main
      - 'release/**'
      - develop

env:
  NEXUS_DOCKER_USER: ${{ secrets.HOME_NEXUS_DOCKER_USER }}

jobs:
  deploy-wordpress:
    runs-on: [ self-hosted, medium, build ]
    container:
      image: nexus.jamesjonesconsulting.com:5443/jamesjonesconsulting/podman-dind-like:latest
      options: --userns=keep-id --group-add keep-groups --privileged --user root --security-opt seccomp=unconfined
      credentials:
        username: ${{ secrets.HOME_NEXUS_DOCKER_USER }}
        password: ${{ secrets.HOME_NEXUS_DOCKER_PASSWORD }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
